AWSTemplateFormatVersion: 2010-09-09

Parameters:
  NamePrefix:
    Type: String

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: "Name"
          Value: !Sub "${NamePrefix}-VPC"

  mySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: "Name"
          Value: !Sub "${NamePrefix}-Subnet"

  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow http to remote host"
      VpcId: !Ref myVPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: !Sub "${NamePrefix}-SecurityGroup"

Outputs:
  SubnetId:
    Value: !Ref mySubnet
  SecurityGroupId:
    Value: !Ref mySecurityGroup
